// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADgFzl9hGXRXe1eLwiiAKttTlzQVL1jVc',
    appId: '1:791951952593:web:8b43a7ffd3bf22137413f0',
    messagingSenderId: '791951952593',
    projectId: 'zartek-17c3b',
    authDomain: 'zartek-17c3b.firebaseapp.com',
    storageBucket: 'zartek-17c3b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr_aJLg0BGhxDDSOUSYLeDwCXq880la-8',
    appId: '1:791951952593:android:635c8389f9afe3a27413f0',
    messagingSenderId: '791951952593',
    projectId: 'zartek-17c3b',
    storageBucket: 'zartek-17c3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_CHY0_lMZjsyHB3kat0FYzn_wR51-ha4',
    appId: '1:791951952593:ios:b5484246fbc414c57413f0',
    messagingSenderId: '791951952593',
    projectId: 'zartek-17c3b',
    storageBucket: 'zartek-17c3b.firebasestorage.app',
    iosBundleId: 'com.example.zartek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_CHY0_lMZjsyHB3kat0FYzn_wR51-ha4',
    appId: '1:791951952593:ios:b5484246fbc414c57413f0',
    messagingSenderId: '791951952593',
    projectId: 'zartek-17c3b',
    storageBucket: 'zartek-17c3b.firebasestorage.app',
    iosBundleId: 'com.example.zartek',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADgFzl9hGXRXe1eLwiiAKttTlzQVL1jVc',
    appId: '1:791951952593:web:274a5884aba49d967413f0',
    messagingSenderId: '791951952593',
    projectId: 'zartek-17c3b',
    authDomain: 'zartek-17c3b.firebaseapp.com',
    storageBucket: 'zartek-17c3b.firebasestorage.app',
  );
}
